// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PokemonAPI.Infrastructure.Persistence;

#nullable disable

namespace PokemonAPI.Migrations
{
    [DbContext(typeof(PokemonDbContext))]
    [Migration("20260506084306_AddUsersAuthentication")]
    partial class AddUsersAuthentication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PokemonAPI.Features.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "AQAAAAIAAYagAAAAEEzwJw/OusEw9Qa1Zs0EGpttmGHcgXhI65/HGUQt2FoHcN+U991dzYxnqZ88pQ+vfw==",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("PokemonAPI.Features.Pokemons.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("pokemons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 5,
                            Name = "scyther",
                            Type = "air"
                        },
                        new
                        {
                            Id = 2,
                            Age = 9,
                            Name = "lapras",
                            Type = "water"
                        },
                        new
                        {
                            Id = 3,
                            Age = 7,
                            Name = "arcanine",
                            Type = "fire"
                        },
                        new
                        {
                            Id = 4,
                            Age = 11,
                            Name = "alakazam",
                            Type = "air"
                        },
                        new
                        {
                            Id = 5,
                            Age = 8,
                            Name = "gyarados",
                            Type = "water"
                        },
                        new
                        {
                            Id = 6,
                            Age = 4,
                            Name = "jolteon",
                            Type = "air"
                        },
                        new
                        {
                            Id = 7,
                            Age = 3,
                            Name = "clefairy",
                            Type = "air"
                        },
                        new
                        {
                            Id = 8,
                            Age = 10,
                            Name = "onix",
                            Type = "air"
                        },
                        new
                        {
                            Id = 9,
                            Age = 6,
                            Name = "starmie",
                            Type = "water"
                        },
                        new
                        {
                            Id = 10,
                            Age = 2,
                            Name = "ditto",
                            Type = "air"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
