// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PokemonAPI.Infrastructure.Persistence;

#nullable disable

namespace PokemonAPI.Migrations
{
    [DbContext(typeof(PokemonDbContext))]
    [Migration("20260505122745_SeedTenPokemon")]
    partial class SeedTenPokemon
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PokemonAPI.Features.Pokemons.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("pokemons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "scyther"
                        },
                        new
                        {
                            Id = 2,
                            Name = "lapras"
                        },
                        new
                        {
                            Id = 3,
                            Name = "arcanine"
                        },
                        new
                        {
                            Id = 4,
                            Name = "alakazam"
                        },
                        new
                        {
                            Id = 5,
                            Name = "gyarados"
                        },
                        new
                        {
                            Id = 6,
                            Name = "jolteon"
                        },
                        new
                        {
                            Id = 7,
                            Name = "clefairy"
                        },
                        new
                        {
                            Id = 8,
                            Name = "onix"
                        },
                        new
                        {
                            Id = 9,
                            Name = "starmie"
                        },
                        new
                        {
                            Id = 10,
                            Name = "ditto"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
