// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PokemonAPI.Infrastructure.Persistence;

#nullable disable

namespace PokemonAPI.Migrations
{
    [DbContext(typeof(PokemonDbContext))]
    partial class PokemonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PokemonAPI.Features.Pokemons.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("pokemons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 5,
                            Name = "scyther",
                            Type = "hava"
                        },
                        new
                        {
                            Id = 2,
                            Age = 9,
                            Name = "lapras",
                            Type = "su"
                        },
                        new
                        {
                            Id = 3,
                            Age = 7,
                            Name = "arcanine",
                            Type = "ateş"
                        },
                        new
                        {
                            Id = 4,
                            Age = 11,
                            Name = "alakazam",
                            Type = "hava"
                        },
                        new
                        {
                            Id = 5,
                            Age = 8,
                            Name = "gyarados",
                            Type = "su"
                        },
                        new
                        {
                            Id = 6,
                            Age = 4,
                            Name = "jolteon",
                            Type = "hava"
                        },
                        new
                        {
                            Id = 7,
                            Age = 3,
                            Name = "clefairy",
                            Type = "hava"
                        },
                        new
                        {
                            Id = 8,
                            Age = 10,
                            Name = "onix",
                            Type = "hava"
                        },
                        new
                        {
                            Id = 9,
                            Age = 6,
                            Name = "starmie",
                            Type = "su"
                        },
                        new
                        {
                            Id = 10,
                            Age = 2,
                            Name = "ditto",
                            Type = "hava"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
