@PokemonAPI_HostAddress = http://localhost:5102

# OpenAPI document (Development only)
GET {{PokemonAPI_HostAddress}}/openapi/v1.json

###

# Pokemons
GET {{PokemonAPI_HostAddress}}/pokemons

###

GET {{PokemonAPI_HostAddress}}/pokemons?search=ra

###

GET {{PokemonAPI_HostAddress}}/pokemons?search=

###

@PokemonId = 1
GET {{PokemonAPI_HostAddress}}/pokemons/{{PokemonId}}

###
